### ISSUE TITLE
Old log4j dependecies versions in wso-artifacts

### ISSUE THREAD

**Issue by ramiroll** [wso2/maven-tools#102]
I confirmed that this two dependencies contains the following log4j versions:

Maven-car-deploy-plugin[2]:
log4j
log4j
jar
1.2.14

Maven-car-plugin[3]:
log4j
log4j
jar
1.2.12

I tested with a sample project created from the integration studio, removed from my .m2 repository folder the log4j 1.2.14 folder and can observe the same version as the customer mention being pulled from the wso repository:

[INFO] Downloading from wso2-nexus: https://maven.wso2.org/nexus/content/groups/wso2-public/log4j/log4j/1.2.14/log4j-1.2.14.pom

[INFO] Downloaded from wso2-nexus: https://maven.wso2.org/nexus/content/groups/wso2-public/log4j/log4j/1.2.14/log4j-1.2.14.pom (2.4 kB at 1.8 kB/s)

[INFO] Downloading from wso2-nexus: https://maven.wso2.org/nexus/content/groups/wso2-public/log4j/log4j/1.2.14/log4j-1.2.14.jar

[INFO] Downloaded from wso2-nexus: https://maven.wso2.org/nexus/content/groups/wso2-public/log4j/log4j/1.2.14/log4j-1.2.14.jar (367 kB at 333 kB/s)

We got a request from a customer that wants the 2.17.2 version or later.

Please help us by providing your analysis over this. Do you think it is necessary to update the log4j version? If this is the case, would it be updated with a new artifact?

**Comment by DinithHerath** [comment]
Affected other plugins:

- maven-carbon-ui-plugin
- maven-datasource-plugin
- wso2-esb-metadata-plugin
- wso2-general-project-plugin
- humantask-maven-plugin
