### ISSUE TITLE
Can the fixed CompositeApplication name be removed when using vscode-car-plugin?

### ISSUE THREAD

**Issue by thijsvolders** [wso2/maven-tools#45]
**Description:**
I believe the vscode-car-plugin is an improvement over the previous maven plugins to generate a CAR file from source code. We would like to start using this vscode-car-plugin as primary plugin to generate CAR files now. 
However, when we generate a CAR file and deploy it in EI all those services are prefixed with CompositeApplication. It collides with our naming strategy and unnecessarily clutters the service overview.

I have submitted a pull request which contains the capability to change this. The pull request contains more information on the background and changes done in the plugin. It's a non-breaking change to the current plugin!

Please see PR: https://github.com/wso2/maven-tools/pull/43

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
5.2.11-SNAPSHOT

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Run mvn package on a vscode-plugin org.wso2.maven:vscode-car-plugin enables project and checkout the naming of the CAR file.

**Related Issues:**

**Comment by thijsvolders** [comment]
@sajithaliyanage : Hi Sajitha, As my other pull request, this is also one that has been waiting for review for a long time. Can you also please review this? I'm unable to change the reviewers.
Many thanks!
With regards,
Thijs

**Comment by sajithaliyanage** [comment]
@thijsvolders Hi, As per the comment https://github.com/wso2/maven-tools/pull/43#issuecomment-618954192 this is now fixed. Hence, closing this issue. Thanks for your contribution.
