### ISSUE TITLE
 wso2-mi-config-mapper: Download of template.zip fails

### ISSUE THREAD

**Issue by thomas-gantenbein-tga** [wso2/maven-tools#78]
**Description:**
Running `mvn clean package` on a Docker project fails with the following message:
```
[ERROR] Failed to execute goal org.wso2.maven:mi-container-config-mapper:5.2.32:config-mapper-parser (config-mapper-parser) on project mch_docker_curt_wso2mi: Exception while parsing the deployment.toml file
[ERROR] net.lingala.zip4j.exception.ZipException: Probably not a zip file or a corrupted zip file
```
And indeed, when opening the zip file in `projectlocation/null/ConfigMapResources/templates.zip`, what I see is not a zip file but the following HTML:
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://product-dist.wso2.com/p2/templates/1.1.0/templates.zip">here</a>.</p>
<hr>
<address>Apache Server at product-dist.wso2.com Port 80</address>
</body></html>
```
Suggest to change https://github.com/wso2/maven-tools/blob/master/wso2-mi-config-mapper/src/main/java/org/wso2/config/mapper/ConfigMapParserConstants.java#L38 to https instead of http.

I checked out a previous release that once could be successfully built, tried rebuilding it, and it failed. So this does not seem to be an issue with my POM or Carbon application. I think it worked until at least 2021-01-12 15:00 CET.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
* 5.2.32
* 5.2.18

**OS, DB, other environment details and versions:**  
* CentOS 7
* Maven 3.6.3
* miVersion: 1.1.0

**Steps to reproduce:**
* Create Docker project in Integration Studio
* Activate `automatically deploy configurations` or edit pom.xml to achieve the same effect
* Execute `mvn clean package`

**Related Issues:**

**Comment by thomas-gantenbein-tga** [comment]
Update: The build _does_ work again. Either I am seeing ghosts or there used to be (between 12. January and now) a redirect from http://product-dist.wso2.com/p2/templates/1.1.0/templates.zip to https://product-dist.wso2.com/p2/templates/1.1.0/templates.zip. That redirect is gone by now, which "fixes" this issue but maybe the code could be adapted to follow redirects if ever someone decides again to introduce a redirect on the download server.

**Comment by rellbits** [comment]
I just hit this same issue today when trying to build a docker image through the IDE (WSO2 Integration Studio). The template zip file is corrupted. Please reopen this issue so that they become aware that something is still wrong with the config mapper parser.
@sajinieKavindya

**Comment by thomas-gantenbein-tga** [comment]
So I am not seeing ghosts, after all. Thanks, @rellbits. The build fails again and the redirect is there again, too.

Here's part of the output of `curl http://product-dist.wso2.com/p2/templates/1.1.0/templates.zip -v`. The HTML at the end of the output below is what will end put *being* the zip file. So no wonder a ZipException is raised when trying to unzip that.
```
> GET /p2/templates/1.1.0/templates.zip HTTP/1.1
> Host: product-dist.wso2.com
> User-Agent: curl/7.64.0
> Accept: */*
> 
< HTTP/1.1 302 Found
< Date: Sun, 31 Jan 2021 13:39:14 GMT
< Server: Apache
< X-Frame-Options: SAMEORIGIN
< Location: https://product-dist.wso2.com/p2/templates/1.1.0/templates.zip
< Content-Length: 317
< Content-Type: text/html; charset=iso-8859-1
< 
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://product-dist.wso2.com/p2/templates/1.1.0/templates.zip">here</a>.</p>
<hr>
<address>Apache Server at product-dist.wso2.com Port 80</address>
</body></html>
```

**Comment by sanethmaduranga** [comment]
Try with the latest 'mi-container-config-mapper' version of 5.2.36.
Refer to the https://mvnrepository.com/artifact/org.wso2.maven/mi-container-config-mapper/5.2.36 .

**Comment by thomas-gantenbein-tga** [comment]
Thank @sanethmaduranga. I haven't tested (I have just deactivated automatic deployment of configurations and used an existing docker file), but seeing your commit [77057b8](https://github.com/wso2/maven-tools/commit/77057b8f4b257b6098b2a5d162eb639f6ca5e9a0#diff-202a93f9536499da4e850ed47d00fa9c255160d3532766f90d71458b1bc59242), I'm sure this issue can be closed.

**Comment by urbiso** [comment]
I've followed @sanethmaduranga comment and changed the version of the **mi-container-config-mapper** in the pom.xml with in the project folder from <version>5.2.28</version> to **<version>5.2.36</version>** and the build start to work.

**Comment by squall8985** [comment]
Hi i had the same issue and it trying to download the templates.zip from internet. But my build machine is behind internet and i have no access. How do i workaround for this?

**Comment by thomas-gantenbein-tga** [comment]
Hi, @squall8985, a workaround that should work (though I haven't thought this through): 
* Just deactivate the checkbox "automatically deploy configurations" and see if the build and application still do what you expect. That checkbox isn't always needed.

If that does not work:
* Copy your project -- or indeed: create a new project -- on a machine that _does_ have Internet access.
* Have git track that project
* Start a build there.
* Identify the new files with the help of git and consider the automatically generated new lines in `Dockerfile`.
* Copy over the new files to your machine without Internet access (that would be the unzipped stuff from template.zip and maybe some other stuff).
* Add the automatically generated new lines to your `Dockerfile` on the machine without Internet access.
* Make sure all the files that are referenced in the `Dockerfile` do exist. Copy over more stuff if needed.
* Deactivate the checkbox "automatically deploy configurations"
* Retry the build.

This should make the build behave _as if_ the checkbox was activated, but nothing will need to be downloaded.
